---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true
  use_vagrant_berkshelf_plugin: true

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver:
      box: centos65-x86_64-20140116
      box_url: https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box

suites:
  - name: default
    run_list:
        - recipe[cb-common::default]
    attributes:
