source 'https://rubygems.org'

gem 'berkshelf'

group :plugins do
  gem 'vagrant-omnibus'
  gem 'vagrant-berkshelf'
end

group :development do
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
  gem 'foodcritic'
  gem 'guard'
  gem 'guard-kitchen'
  gem 'chefspec'
  gem 'serverspec'
end
