source 'https://rubygems.org'

gem 'berkshelf'

group :plugins do
  gem 'vagrant-omnibus'
  gem 'vagrant-berkshelf'
end

group :development do
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
  gem 'guard'
  gem 'guard-kitchen'
  gem 'guard-foodcritic', :git => "git://github.com/miketheman/guard-foodcritic.git", :branch => "patch-1"
  gem 'foodcritic', '>= 4.0'
  gem 'chefspec', '>= 3.1'
end
