name 'cb-common'
maintainer 'Frank Kline'
maintainer_email 'frank.kline@gmail.com'
license 'All rights reserved'
description 'Installs/Configures cb-common'
long_description 'Installs/Configures cb-common'
version '0.3.0'

depends 'ntp', '= 1.6.4'
depends 'timezone-ii', '= 0.2.0'
